/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import InternalPages.Accounts;
import java.awt.Color;
import java.awt.Desktop;
import java.net.URL;
import javax.swing.JOptionPane;

/**
 *
 * @author Rhai
 */
public class DashboardMenu extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public DashboardMenu() {
        initComponents();
    }
    
    Color hovbtn = new Color(69,60,240);
    Color defbtn = new Color(126,120,240);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_pnl = new javax.swing.JPanel();
        AccSettings_btn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Hello_lbl1 = new javax.swing.JLabel();
        Apprhai_ico = new javax.swing.JLabel();
        Logout_btn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Dash3_pnl = new javax.swing.JPanel();
        DC_btn = new javax.swing.JPanel();
        DC_ico = new javax.swing.JLabel();
        join_lbl = new javax.swing.JLabel();
        FB_btn = new javax.swing.JPanel();
        FB_ico = new javax.swing.JLabel();
        follow_lbl = new javax.swing.JLabel();
        BG_img = new javax.swing.JLabel();
        top_pnl = new javax.swing.JPanel();
        minimize_btn = new javax.swing.JLabel();
        close_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BG_pnl.setBackground(new java.awt.Color(204, 202, 240));
        BG_pnl.setPreferredSize(new java.awt.Dimension(850, 500));
        BG_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AccSettings_btn.setBackground(new java.awt.Color(126, 120, 240));
        AccSettings_btn.setPreferredSize(new java.awt.Dimension(150, 150));
        AccSettings_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccSettings_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AccSettings_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AccSettings_btnMouseExited(evt);
            }
        });
        AccSettings_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePackage/icons8-account-100 (1).png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        AccSettings_btn.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 150, 110));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DASHBOARD");
        AccSettings_btn.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 150, 40));

        BG_pnl.add(AccSettings_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 152, -1));

        Hello_lbl1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Hello_lbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Hello_lbl1.setText("Hello, User");
        BG_pnl.add(Hello_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 270, 80));

        Apprhai_ico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Apprhai_ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePackage/cafe-removebg-preview.png"))); // NOI18N
        BG_pnl.add(Apprhai_ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 100, 130));

        Logout_btn.setBackground(new java.awt.Color(126, 120, 240));
        Logout_btn.setPreferredSize(new java.awt.Dimension(150, 150));
        Logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Logout_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Logout_btnMouseExited(evt);
            }
        });
        Logout_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOG OUT");
        Logout_btn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 150, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePackage/icons8-logout-100.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Logout_btn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 150, 110));

        BG_pnl.add(Logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        Dash3_pnl.setBackground(new java.awt.Color(126, 120, 240));
        Dash3_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DC_btn.setBackground(new java.awt.Color(102, 102, 255));
        DC_btn.setPreferredSize(new java.awt.Dimension(230, 215));
        DC_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DC_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DC_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DC_btnMouseExited(evt);
            }
        });
        DC_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DC_ico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DC_ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePackage/instagram icon.png"))); // NOI18N
        DC_btn.add(DC_ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 170));

        join_lbl.setBackground(new java.awt.Color(51, 51, 51));
        join_lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        join_lbl.setForeground(new java.awt.Color(255, 255, 255));
        join_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        join_lbl.setText("Join Us!");
        DC_btn.add(join_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 230, 30));

        Dash3_pnl.add(DC_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, -1));

        FB_btn.setBackground(new java.awt.Color(102, 102, 255));
        FB_btn.setPreferredSize(new java.awt.Dimension(230, 215));
        FB_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FB_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FB_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FB_btnMouseExited(evt);
            }
        });
        FB_btn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FB_ico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FB_ico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePackage/facebook (1).png"))); // NOI18N
        FB_btn.add(FB_ico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 170));

        follow_lbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        follow_lbl.setForeground(new java.awt.Color(255, 255, 255));
        follow_lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        follow_lbl.setText("Follow Me!");
        FB_btn.add(follow_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 230, 45));

        Dash3_pnl.add(FB_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 215, 230, -1));

        BG_pnl.add(Dash3_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 230, 430));

        BG_img.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BG_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePackage/full backg.jpg"))); // NOI18N
        BG_pnl.add(BG_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 510));

        getContentPane().add(BG_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        top_pnl.setBackground(new java.awt.Color(69, 60, 240));
        top_pnl.setPreferredSize(new java.awt.Dimension(850, 50));
        top_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minimize_btn.setForeground(new java.awt.Color(255, 255, 255));
        minimize_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize_btn.setText("—");
        minimize_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_btnMouseClicked(evt);
            }
        });
        top_pnl.add(minimize_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 30, 30));

        close_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close_btn.setForeground(new java.awt.Color(255, 255, 255));
        close_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_btn.setText("X");
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
        });
        top_pnl.add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        getContentPane().add(top_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimize_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_btnMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimize_btnMouseClicked

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        DashboardFrame df = new DashboardFrame();
        this.dispose();
        df.setVisible(true);
    }//GEN-LAST:event_close_btnMouseClicked

    private void DC_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DC_btnMouseClicked
        try{
            
            Desktop.getDesktop().browse(new URL("https://instagram.com/angel_gabutero?igshid=ZGUzMzM3NWJiOQ==").toURI());
            
        }
        catch(Exception e){}
    }//GEN-LAST:event_DC_btnMouseClicked

    private void FB_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FB_btnMouseClicked
        try{
            
            Desktop.getDesktop().browse(new URL("https://www.facebook.com/angelgabutero20").toURI());
            
        }
        catch(Exception e){}
    }//GEN-LAST:event_FB_btnMouseClicked

    private void DC_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DC_btnMouseEntered
        DC_btn.setBackground(hovbtn);
    }//GEN-LAST:event_DC_btnMouseEntered

    private void FB_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FB_btnMouseEntered
        FB_btn.setBackground(hovbtn);
    }//GEN-LAST:event_FB_btnMouseEntered

    private void DC_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DC_btnMouseExited
        DC_btn.setBackground(defbtn);
    }//GEN-LAST:event_DC_btnMouseExited

    private void FB_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FB_btnMouseExited
        FB_btn.setBackground(defbtn);
    }//GEN-LAST:event_FB_btnMouseExited

    private void Logout_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_btnMouseExited
        Logout_btn.setBackground(defbtn);
    }//GEN-LAST:event_Logout_btnMouseExited

    private void Logout_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_btnMouseEntered
        Logout_btn.setBackground(hovbtn);
    }//GEN-LAST:event_Logout_btnMouseEntered

    private void Logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_btnMouseClicked

        int ans = JOptionPane.showConfirmDialog( null,"Do you want to log out?", "Notice!", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if(ans == JOptionPane.YES_OPTION){

            LoginFrame lframe = new LoginFrame();
            lframe.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_Logout_btnMouseClicked

    private void AccSettings_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccSettings_btnMouseExited
        AccSettings_btn.setBackground(defbtn);
    }//GEN-LAST:event_AccSettings_btnMouseExited

    private void AccSettings_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccSettings_btnMouseEntered
        AccSettings_btn.setBackground(hovbtn);
    }//GEN-LAST:event_AccSettings_btnMouseEntered

    private void AccSettings_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccSettings_btnMouseClicked
        this.dispose();
        DashboardFrame df = new DashboardFrame();
        df.setVisible(true);
        Accounts up = new Accounts();
        df.desk_pnl.add(up).setVisible(true);
    }//GEN-LAST:event_AccSettings_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccSettings_btn;
    private javax.swing.JLabel Apprhai_ico;
    private javax.swing.JLabel BG_img;
    private javax.swing.JPanel BG_pnl;
    private javax.swing.JPanel DC_btn;
    private javax.swing.JLabel DC_ico;
    private javax.swing.JPanel Dash3_pnl;
    private javax.swing.JPanel FB_btn;
    private javax.swing.JLabel FB_ico;
    private javax.swing.JLabel Hello_lbl1;
    private javax.swing.JPanel Logout_btn;
    private javax.swing.JLabel close_btn;
    private javax.swing.JLabel follow_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel join_lbl;
    private javax.swing.JLabel minimize_btn;
    private javax.swing.JPanel top_pnl;
    // End of variables declaration//GEN-END:variables
}
