/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import InternalPages.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Rhai
 */
public class DashboardFrame extends javax.swing.JFrame {

    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
        initComponents();
        
        Customer up = new Customer();
        desk_pnl.add(up).setVisible(true);
        
    }
    
    Color hovbtn = new Color(69,60,240);
    Color defbtn = new Color(126,120,240);
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_pnl = new javax.swing.JPanel();
        side_pnl = new javax.swing.JPanel();
        customer_btn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        product_btn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        order_btn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        orderitem_btn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        dashboard_btn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        top_pnl = new javax.swing.JPanel();
        minimize_btn = new javax.swing.JLabel();
        close_btn = new javax.swing.JLabel();
        desk_pnl = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BG_pnl.setBackground(new java.awt.Color(204, 202, 240));
        BG_pnl.setPreferredSize(new java.awt.Dimension(1050, 550));
        BG_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pnl.setBackground(new java.awt.Color(126, 120, 240));
        side_pnl.setPreferredSize(new java.awt.Dimension(200, 550));
        side_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customer_btn.setBackground(new java.awt.Color(126, 120, 240));
        customer_btn.setPreferredSize(new java.awt.Dimension(200, 60));
        customer_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customer_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                customer_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                customer_btnMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer");

        javax.swing.GroupLayout customer_btnLayout = new javax.swing.GroupLayout(customer_btn);
        customer_btn.setLayout(customer_btnLayout);
        customer_btnLayout.setHorizontalGroup(
            customer_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customer_btnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        customer_btnLayout.setVerticalGroup(
            customer_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customer_btnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        side_pnl.add(customer_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 213, -1, -1));

        product_btn.setBackground(new java.awt.Color(126, 120, 240));
        product_btn.setPreferredSize(new java.awt.Dimension(200, 60));
        product_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                product_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                product_btnMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Product");

        javax.swing.GroupLayout product_btnLayout = new javax.swing.GroupLayout(product_btn);
        product_btn.setLayout(product_btnLayout);
        product_btnLayout.setHorizontalGroup(
            product_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_btnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        product_btnLayout.setVerticalGroup(
            product_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, product_btnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        side_pnl.add(product_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 274, 200, -1));

        order_btn.setBackground(new java.awt.Color(126, 120, 240));
        order_btn.setPreferredSize(new java.awt.Dimension(200, 60));
        order_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                order_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                order_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                order_btnMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Order");

        javax.swing.GroupLayout order_btnLayout = new javax.swing.GroupLayout(order_btn);
        order_btn.setLayout(order_btnLayout);
        order_btnLayout.setHorizontalGroup(
            order_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, order_btnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        order_btnLayout.setVerticalGroup(
            order_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, order_btnLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        side_pnl.add(order_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 335, -1, -1));

        orderitem_btn.setBackground(new java.awt.Color(126, 120, 240));
        orderitem_btn.setPreferredSize(new java.awt.Dimension(200, 60));
        orderitem_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderitem_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                orderitem_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                orderitem_btnMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Order Item");

        javax.swing.GroupLayout orderitem_btnLayout = new javax.swing.GroupLayout(orderitem_btn);
        orderitem_btn.setLayout(orderitem_btnLayout);
        orderitem_btnLayout.setHorizontalGroup(
            orderitem_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        orderitem_btnLayout.setVerticalGroup(
            orderitem_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderitem_btnLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        side_pnl.add(orderitem_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 396, 200, -1));

        dashboard_btn.setBackground(new java.awt.Color(126, 120, 240));
        dashboard_btn.setPreferredSize(new java.awt.Dimension(200, 60));
        dashboard_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboard_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboard_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboard_btnMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Dashboard");

        javax.swing.GroupLayout dashboard_btnLayout = new javax.swing.GroupLayout(dashboard_btn);
        dashboard_btn.setLayout(dashboard_btnLayout);
        dashboard_btnLayout.setHorizontalGroup(
            dashboard_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboard_btnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dashboard_btnLayout.setVerticalGroup(
            dashboard_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboard_btnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        side_pnl.add(dashboard_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 152, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagePackage/cafe-removebg-preview.png"))); // NOI18N
        side_pnl.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, 140));

        BG_pnl.add(side_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        top_pnl.setBackground(new java.awt.Color(69, 60, 240));
        top_pnl.setPreferredSize(new java.awt.Dimension(850, 50));
        top_pnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        minimize_btn.setForeground(new java.awt.Color(255, 255, 255));
        minimize_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize_btn.setText("—");
        minimize_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimize_btnMouseClicked(evt);
            }
        });
        top_pnl.add(minimize_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 30, 30));

        close_btn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close_btn.setForeground(new java.awt.Color(255, 255, 255));
        close_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close_btn.setText("X");
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
        });
        top_pnl.add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        BG_pnl.add(top_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 850, -1));

        javax.swing.GroupLayout desk_pnlLayout = new javax.swing.GroupLayout(desk_pnl);
        desk_pnl.setLayout(desk_pnlLayout);
        desk_pnlLayout.setHorizontalGroup(
            desk_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        desk_pnlLayout.setVerticalGroup(
            desk_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        BG_pnl.add(desk_pnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 850, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BG_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BG_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimize_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimize_btnMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimize_btnMouseClicked

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        int a = JOptionPane.showConfirmDialog(null, "Confirm Exit?");
        if(a == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_close_btnMouseClicked

    private void customer_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_btnMouseClicked
        Customer up = new Customer();
        desk_pnl.add(up).setVisible(true);
    }//GEN-LAST:event_customer_btnMouseClicked

    private void product_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_btnMouseClicked
        Product up = new Product();
        desk_pnl.add(up).setVisible(true);
    }//GEN-LAST:event_product_btnMouseClicked

    private void order_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_order_btnMouseClicked
        Order up = new Order();
        desk_pnl.add(up).setVisible(true);
    }//GEN-LAST:event_order_btnMouseClicked

    private void orderitem_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderitem_btnMouseClicked
        OrderItem up = new OrderItem();
        desk_pnl.add(up).setVisible(true);
    }//GEN-LAST:event_orderitem_btnMouseClicked

    private void dashboard_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_btnMouseClicked
        DashboardMenu dash = new DashboardMenu();
        this.dispose();
        dash.setVisible(true);
    }//GEN-LAST:event_dashboard_btnMouseClicked

    private void customer_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_btnMouseEntered
        customer_btn.setBackground(hovbtn);
    }//GEN-LAST:event_customer_btnMouseEntered

    private void product_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_btnMouseEntered
        product_btn.setBackground(hovbtn);
    }//GEN-LAST:event_product_btnMouseEntered

    private void order_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_order_btnMouseEntered
        order_btn.setBackground(hovbtn);
    }//GEN-LAST:event_order_btnMouseEntered

    private void orderitem_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderitem_btnMouseEntered
        orderitem_btn.setBackground(hovbtn);
    }//GEN-LAST:event_orderitem_btnMouseEntered

    private void dashboard_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_btnMouseEntered
        dashboard_btn.setBackground(hovbtn);
    }//GEN-LAST:event_dashboard_btnMouseEntered

    private void customer_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customer_btnMouseExited
        customer_btn.setBackground(defbtn);
    }//GEN-LAST:event_customer_btnMouseExited

    private void product_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_btnMouseExited
        product_btn.setBackground(defbtn);
    }//GEN-LAST:event_product_btnMouseExited

    private void order_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_order_btnMouseExited
        order_btn.setBackground(defbtn);
    }//GEN-LAST:event_order_btnMouseExited

    private void orderitem_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderitem_btnMouseExited
        orderitem_btn.setBackground(defbtn);
    }//GEN-LAST:event_orderitem_btnMouseExited

    private void dashboard_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboard_btnMouseExited
        dashboard_btn.setBackground(defbtn);
    }//GEN-LAST:event_dashboard_btnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_pnl;
    private javax.swing.JLabel close_btn;
    private javax.swing.JPanel customer_btn;
    private javax.swing.JPanel dashboard_btn;
    public javax.swing.JDesktopPane desk_pnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel minimize_btn;
    private javax.swing.JPanel order_btn;
    private javax.swing.JPanel orderitem_btn;
    private javax.swing.JPanel product_btn;
    private javax.swing.JPanel side_pnl;
    private javax.swing.JPanel top_pnl;
    // End of variables declaration//GEN-END:variables
}
